//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 VehicleInfo.rc 使用
//
#define IDM_ABOUTBOX                    0x0010
#define IDS_ABOUTBOX                    101
#define IDD_VEHICLEINFO_DIALOG          102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDD_REALTIMERECV                130
#define IDD_QUERY                       131
#define IDD_ALERTDATA                   132
#define IDD_STATISTICS                  134
#define IDD_ALERTRANK                   136
#define IDD_ALERTCATEGORY               138
#define IDC_TAB1                        1000
#define IDC_EDIT_VINCODE                1001
#define IDC_STATIC_VINCODE              1002
#define IDC_EDIT_GATHERTIME             1003
#define IDC_STATIC_GATHERTIME           1004
#define IDC_STATIC_VEHICLESTATE         1005
#define IDC_EDIT_VEHICLESTATE           1006
#define IDC_STATIC_RECHARGESTATE        1007
#define IDC_EDIT_RECHARGESTATE          1008
#define IDC_EDIT_RUNMODE                1009
#define IDC_STATIC_RUNMODE              1010
#define IDC_STATIC_SPEED                1011
#define IDC_EDIT_SPEED                  1012
#define IDC_STATIC_MILEAGE              1013
#define IDC_EDIT_MILEAGE                1014
#define IDC_STATIC_MOTORSTATE           1015
#define IDC_EDIT_MOTORSTATE             1016
#define IDC_STATIC_MOTORROTATESPEED     1017
#define IDC_EDIT_MOTORROTATESPEED       1018
#define IDC_STATIC_MOTORTORQUE          1019
#define IDC_EDIT__MOTORTORQUE           1020
#define IDC_STATIC_MILEAGE2             1020
#define IDC_STATIC_MOTORTEMP            1021
#define IDC_EDIT__MOTORTEMP             1022
#define IDC_EDIT_MILEAGETODAY           1022
#define IDC_STATIC_MAXVOLTNO            1023
#define IDC_EDIT_MAXVOLTNO              1024
#define IDC_STATIC_VOLTMAXVALUE         1025
#define IDC_EDIT_VOLTMAXVALUE           1026
#define IDC_STATIC_MINVOLTNO            1027
#define IDC_EDIT_MINVOLTNO              1028
#define IDC_STATIC_VOLTMINVALUE         1029
#define IDC_EDIT_VOLTMINVALUE           1030
#define IDC_STATIC_MAXTEMPPROPNO        1031
#define IDC_EDIT_MAXTEMPPROPNO          1032
#define IDC_STATIC_MAXTEMPVALUE         1033
#define IDC_EDIT_MAXTEMPVALUE           1034
#define IDC_STATIC_MINTEMPPROPNO        1035
#define IDC_EDIT_MINTEMPPROPNO          1036
#define IDC_STATIC_MINTEMPVALUE         1037
#define IDC_EDIT_MINTEMPVALUE           1038
#define IDC_STATIC_LOCATIONSTATE        1039
#define IDC_EDIT_LOCATIONSTATE          1040
#define IDC_STATIC_LONGTITUDE           1041
#define IDC_EDIT_LONGTITUDE             1042
#define IDC_STATIC_LATITUDE             1043
#define IDC_EDIT__LATITUDE              1044
#define IDC_EDIT_MOTORTORQUE            1045
#define IDC_EDIT_MOTORTEMP              1046
#define IDC_STATIC_MOTORSTATE2          1047
#define IDC_EDIT_LATITUDE               1047
#define IDC_EDIT_MOTORSTATE2            1048
#define IDC_BTN_QUERY                   1048
#define IDC_STATIC_MOTORROTATESPEED2    1049
#define IDC_BTN_MAPLOCATION             1049
#define IDC_EDIT_MOTORROTATESPEED2      1050
#define IDC_BTN_ALERTDATA               1050
#define IDC_STATIC_MOTORTORQUE2         1051
#define IDC_BUTTON2                     1051
#define IDC_BTN_DIAGNOSIS               1051
#define IDC_EDIT__MOTORTORQUE2          1052
#define IDC_STATIC9                     1052
#define IDC_STATIC_MOTORTEMP2           1053
#define IDC_STATIC10                    1053
#define IDC_BTN_REFRESH                 1053
#define IDC_EDIT__MOTORTEMP2            1054
#define IDC_STATIC0                     1054
#define IDC_EDIT_VEHICLESUM             1054
#define IDC_STATIC1                     1055
#define IDC_EDIT_VEHICLEONLINE          1055
#define IDC_STATIC2                     1056
#define IDC_EDIT_MILEAGESUN             1056
#define IDC_STATIC3                     1057
#define IDC_EDIT_CARBONEMISSION         1057
#define IDC_STATIC4                     1058
#define IDC_EDIT_FUELTHRIFT             1058
#define IDC_STATIC5                     1059
#define IDC_EDIT_POWERCONSUME           1059
#define IDC_STATIC6                     1060
#define IDC_EDIT_VEHICLEONLINETODAY     1060
#define IDC_STATIC7                     1061
#define IDC_EDIT_VEHICLERECHARGETODAY   1061
#define IDC_STATIC8                     1062
#define IDC_EDIT_VEHICLEFAULTTODAY      1062
#define IDC_STATIC11                    1063
#define IDC_EDIT_VEHICLEOFFLINETODAY    1063
#define IDC_STATIC12                    1064
#define IDC_EDIT_VEHICLEONLINELASTWEEK  1064
#define IDC_STATIC13                    1065
#define IDC_EDIT_VEHICLERECHARGELASTWEEK 1065
#define IDC_STATIC14                    1066
#define IDC_EDIT_VEHICLEFAULTLASTWEEK   1066
#define IDC_STATIC15                    1067
#define IDC_EDIT_VEHICLEOFFLINELASTWEEK 1067
#define IDC_STATIC16                    1068
#define IDC_EDIT_DATAGRAMSUM            1068
#define IDC_STATIC17                    1069
#define IDC_EDIT_DATAGSIZESUM           1069
#define IDC_EDIT_DATASIZESUM            1069
#define IDC_STATIC18                    1070
#define IDC_EDIT_ALERTVIN               1071
#define IDC_COMBO_RANKTYPE              1072
#define IDC_LIST_RANK                   1074
#define IDC_EDIT_MEMTOTAL               1075
#define IDC_EDIT_VMEMTOTAL              1076
#define IDC_EDIT_MEMFREE                1077
#define IDC_IPADDRESS                   1077
#define IDC_EDIT_VMEMFREE               1078
#define IDC_EDIT_PORT                   1078
#define IDC_BTN_CONNECT                 1079
#define IDC_BTN_DISCONNECT              1080
#define IDC_LIST_CATEGORY               1082
#define IDC_TITLE                       1083
#define IDC_STATIC_MEMTOTAL             1084
#define IDC_STATIC_MEMFREE              1085
#define IDC_STATIC_VMEMTOTAL            1086
#define IDC_STATIC_VMEMFREE             1087
#define IDC_STATIC_B1                   1088
#define IDC_STATIC_B2                   1089
#define IDC_STATIC_B3                   1090
#define IDC_STATIC_B4                   1091

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1092
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
